### PR TITLE
Add HaC Code of Conduct

### PR DESCRIPTION
**Pull request by moosichu**
Make constitution/non-constitutional change from meeting on YYYY-MM-DD

Description of the changes.

Proposed By Tom Read Cutting.

**Attendees**:
  - Name: Role
  - Name: Role

**Votes For**: X

**Votes Against**: X

**Abstentions**: X

**Observing**:
  - Name

### CODE REVIEW

**Comment by CharlieCrisp** [comment]
@moosichu this is looking good although I have some concerns about the wording around sexual language, imagery and clothing. 
Firstly, I think we should make sure that we are not closing off an avenue for a hack where, for instance, a team tries to create a product promoting good sexual health or the like.
I also think that explicitly stating that people shouldn't use sexualised clothing is very subjective and has caused a lot of controversy in the past where people who wear clothing that they believe is appropriate, is considered to be sexualised by other people. 
Do these originate from a standardised code of conduct or were these ad hoc?

**Comment by moosichu** [comment]
@CharlieCrisp These orginate from somewhere else. And I would be strongly inclined to agree with you. 
https://hackcodeofconduct.org/ is the source of this. I didn't want to unanimously change stuff about it myself, but I do agree that it some ways it is really odd in seemingly equating sexuality with harrasment.

**Comment by moosichu** [comment]
@CharlieCrisp I have updated the document to reflect the changes that you have requested. It still says that *unwanted* sexual attention and *inappropriate* physical contact is disallowed. Which should be enough IMO.

**Comment by moosichu** [comment]
I have also undone changes to the constitution, I think adding anything explicit like would be unhelpful.

**Review by jaredkhan — APPROVED** [review]

**Pull request closed without merging**
